version: '3.7'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
  api:
    build: ./server
    ports:
      - '3000:3000'
  